export type SubwayEstimate = {
  station_id: string;
  station_name: string;
  lines: string;
  estimated_walk_minutes: number;
  confidence: string;
  google_maps_directions_url: string | null;
};

export type Listing = {
  id: string;
  canonical_url: string;
  source: string;
  source_listing_id: string | null;
  title: string | null;
  description: string | null;
  address_text: string | null;
  neighborhood: string | null;
  borough: string;
  latitude: number | null;
  longitude: number | null;
  rent: number;
  beds: number;
  baths: number;
  sqft: number | null;
  available_date: string | null;
  nearest_subway_station: string | null;
  nearest_subway_lines: string | null;
  subway_walk_minutes: number | null;
  subway_walk_source: string | null;
  subway_walk_confidence: string | null;
  google_maps_directions_url: string | null;
  manhattan_commute_minutes: number | null;
  fee_status: string | null;
  laundry: string | null;
  dishwasher: number | null;
  outdoor_space: number | null;
  pets: string | null;
  floor_number: number | null;
  elevator: number | null;
  fit_score: number;
  deal_score: number;
  urgency_score: number;
  risk_score: number;
  status: string;
  first_seen_at: string;
  last_seen_at: string;
  created_at: string;
  updated_at: string;
  subway_estimates: SubwayEstimate[];
  amenities: string[];
  image_urls: string[];
};
